stages:
  - test

test:acceptance:
  stage: test
  image: golang:1.15
  except:
    - tags
  script:
    - make testacc
  tags:
    - hc-bladerunner

test:golangci-lint:
  stage: test
  image: golangci/golangci-lint:v1.36
  script:
    - golangci-lint run -v
  except:
    - tags
    - master
  tags:
    - hc-bladerunner
