name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GOTOOLCHAIN: local

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: go test -v -timeout=30s -parallel=8 -coverprofile=coverage.txt -coverpkg=./... ./...

      - uses: codecov/codecov-action@v5
        if: >
          !startsWith(github.head_ref, 'renovate/') &&
          !startsWith(github.head_ref, 'release-please--')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit

  e2e:
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.draft == false
    needs: [unit]
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.tool }}-${{ matrix.version }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: opentofu
            version: v1.8.x
          - tool: opentofu
            version: v1.9.x
          - tool: opentofu
            version: v1.10.x
          - tool: terraform
            version: v1.13.x
          - tool: terraform
            version: v1.14.x

    steps:
      - uses: actions/checkout@v5

      - if: matrix.tool == 'terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false

      - if: matrix.tool == 'opentofu'
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.version }}
          tofu_wrapper: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: hetznercloud/tps-action@main

      - if: matrix.tool == 'opentofu'
        run: |
          echo TF_ACC_TERRAFORM_PATH="$(which tofu)" >> $GITHUB_ENV
          echo TF_ACC_PROVIDER_NAMESPACE="hashicorp" >> $GITHUB_ENV
          echo TF_ACC_PROVIDER_HOST="registry.opentofu.org" >> $GITHUB_ENV

      - run: go test -v -timeout=30m -parallel=8 -coverprofile=coverage.txt -coverpkg=./... ./...
        env:
          # Domain must be available in the account running the tests. This domain is
          # available in the account running the public integration tests.
          CERT_DOMAIN: hc-integrations-test.de

          TF_ACC: 1
          TF_LOG: DEBUG
          TF_LOG_PATH_MASK: test-%s.log

          TEST_DATACENTER: ${{ vars.TEST_DATACENTER }}
          TEST_LOCATION: ${{ vars.TEST_LOCATION }}

      - uses: codecov/codecov-action@v5
        if: >
          !startsWith(github.head_ref, 'renovate/') &&
          !startsWith(github.head_ref, 'releaser-pleaser--')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: e2e

      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: debug-logs-${{ matrix.tool }}-${{ matrix.version }}
          path: internal/**/test-*.log
