name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: make test TESTARGS=-coverprofile=coverage.txt

      - uses: codecov/codecov-action@v3
        with:
          flags: unit

  e2e:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.tool }}-${{ matrix.version }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: opentofu
            version: v1.6.x
          - tool: terraform
            version: v1.6.x
          - tool: terraform
            version: v1.7.x

    steps:
      - uses: actions/checkout@v4

      - if: matrix.tool == 'terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false

      - if: matrix.tool == 'opentofu'
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.version }}
          tofu_wrapper: false

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: hetznercloud/tps-action@main

      - if: matrix.tool == 'opentofu'
        run: |
          echo TF_ACC_TERRAFORM_PATH="$(which tofu)" >> $GITHUB_ENV
          echo TF_ACC_PROVIDER_NAMESPACE="hashicorp" >> $GITHUB_ENV
          echo TF_ACC_PROVIDER_HOST="registry.opentofu.org" >> $GITHUB_ENV

      - run: make testacc TESTARGS="-coverprofile=coverage.txt -coverpkg=./..."
        env:
          # Domain must be available in the account running the tests. This domain is
          # available in the account running the public integration tests.
          CERT_DOMAIN: hc-integrations-test.de

          TF_LOG: DEBUG
          TF_LOG_PATH_MASK: test-%s.log

      - uses: codecov/codecov-action@v3
        with:
          flags: e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-logs-${{ matrix.tool }}-${{ matrix.version }}
          path: internal/**/test-*.log
